# Generated by Django 3.2 on 2021-04-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0004_auto_20210420_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app.Tag'),
        ),
    ]
