# Generated by Django 3.2 on 2021-05-16 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0007_alter_like_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='rating',
        ),
    ]
